import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
  - create an ordered group of docs
  - render a sidebar for each doc of that group
  - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // カリキュラム (学習パス)
  curriculumSidebar: [
    {
      type: 'category',
      label: '学習の始め方',
      items: [
        'curriculum',
        'getting-started',
        'ai-tools-guide',
        'claude-code-best-practices',
      ],
    },
    {
      type: 'category',
      label: '開発フロー',
      items: [
        'develop/dev-workflow',
        'develop/no-aidlc-workflow',
        'develop/aidlc-guide',
        'develop/coding-conventions',
      ],
    },
  ],

  // 本編・仕様 (コア仕様)
  specSidebar: [
    {
      type: 'category',
      label: '概要・用語集',
      items: [
        'overview',
        'glossary',
      ],
    },
    {
      type: 'category',
      label: '仕様書',
      items: [
        'requirements',
        'screen-spec',
        'api-spec',
        'er-diagram',
      ],
    },
    {
      type: 'category',
      label: 'AI-DLC 採用台帳',
      items: [
        'aidlc-adoption',
        'aidlc-audit',
        'aidlc-state',
      ],
    },
  ],

  // リファレンス (参照)
  referenceSidebar: [
    {
      type: 'category',
      label: 'アーキテクチャ',
      items: [
        'architecture',
      ],
    },
    {
      type: 'category',
      label: '設計判断 (ADR)',
      items: [
        {
          type: 'autogenerated',
          dirName: 'reference/adr',
        },
      ],
    },
    {
      type: 'category',
      label: 'Claude Code 設定',
      items: [
        'reference/claude-code/index',
        'reference/claude-code/agent-config',
      ],
    },
  ],

  // 開発ガイド (開発)
  developSidebar: [
    {
      type: 'category',
      label: '開発フロー',
      items: [
        'develop/dev-workflow',
        'develop/no-aidlc-workflow',
        'develop/aidlc-guide',
        'develop/coding-conventions',
        'develop/review-criteria',
        'develop/troubleshooting',
      ],
    },
    {
      type: 'category',
      label: '選択課題カタログ',
      link: {
        type: 'doc',
        id: 'develop/enhancement-catalog',
      },
      items: [
        {
          type: 'category',
          label: 'エンハンス要件カタログ',
          link: {
            type: 'doc',
            id: 'spec/enhancements/index',
          },
          items: [
            {
              type: 'category',
              label: '初級',
              items: [
                'spec/enhancements/resource-list-filter',
                'spec/enhancements/resource-list-sort',
                'spec/enhancements/reservation-list-filter',
                'spec/enhancements/resource-detail-info',
                'spec/enhancements/e2e-test-coverage',
              ],
            },
            {
              type: 'category',
              label: '中級',
              items: [
                'spec/enhancements/recurring-reservation',
                'spec/enhancements/calendar-view',
                'spec/enhancements/usage-statistics',
                'spec/enhancements/csv-export',
                'spec/enhancements/reservation-draft',
              ],
            },
            {
              type: 'category',
              label: '上級',
              items: [
                'spec/enhancements/multi-step-approval',
                'spec/enhancements/department-approver',
                'spec/enhancements/resource-image-upload',
                'spec/enhancements/audit-log',
                'spec/enhancements/openapi-client-gen',
              ],
            },
          ],
        },
      ],
    },
  ],

  // 運用・管理 (運用)
  operationsSidebar: [
    {
      type: 'category',
      label: '運用',
      items: [
        'operations/operations-guide',
        'operations/issue-registration',
        'operations/learning-effectiveness',
      ],
    },
  ],
};

export default sidebars;