import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * サイドバーは docs/ のディレクトリ構造から自動生成する。
 *
 * 手書きで doc ID を列挙していた頃は、ファイルを追加してもサイドバーに載せ忘れる
 * （＝どこからもたどれない孤児ページになる）事故が起きていた。並び順は各ファイルの
 * frontmatter `sidebar_position`、カテゴリのラベル・順序は各ディレクトリの
 * `_category_.json` で決める。1 ファイルは必ず 1 つのサイドバーにだけ属する。
 */
const sidebars: SidebarsConfig = {
  // 学習 — 学習者が最初に読む
  learnSidebar: [{type: 'autogenerated', dirName: 'learn'}],

  // 開発ガイド — 実装中に参照する
  developSidebar: [{type: 'autogenerated', dirName: 'develop'}],

  // 仕様 — 真実の源
  specSidebar: [{type: 'autogenerated', dirName: 'spec'}],

  // リファレンス — 辞書的に引く
  referenceSidebar: [{type: 'autogenerated', dirName: 'reference'}],

  // 運用 — 運営者向け
  operationsSidebar: [{type: 'autogenerated', dirName: 'operations'}],
};

export default sidebars;
